# @package _global_

defaults:
  - model: llama   
  - dataset: speech2latex_llm    
  - training: sft
  - lora: llama
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - _self_

logging_directory: logs
model_directory: models
results_directory: results

# Misc. Settings
normalize_during_preprocessing: false
use_lora: true
use_hyperparameter_search: false

resume_from_checkpoint: false