# @package _global_
model:
  _target_: models.custom_ctc_model.CustomCTCModel
  input_dim: 80
  hidden_dim: 256
  num_classes: 32

processor:
  _target_: transformers.AutoProcessor.from_pretrained
  pretrained_model_name_or_path: "facebook/wav2vec2-base-960h"