# @package _global_

_dataset_base: &base_config
  _target_: datasets.load_dataset
  path: "openslr/librispeech_asr"   
  name: "all"  
  streaming: true

dataset:
  train:
    <<: *base_config
    split: "train.clean.100"

  validation:
    <<: *base_config
    split: "validation.clean"

  test:
    <<: *base_config
    split: "test.clean"

preprocess:
  _target_: data.preprocess.preprocess_librispeech
  _partial_: true