# @package _global_

defaults:
  - model: whisper_small   
  - dataset: speech2latex    
  - training: seq2seq
  - lora: whisper
  - _self_

logging_directory: logs
model_directory: models
results_directory: results

# Misc. Settings
normalize_during_preprocessing: false
use_lora: false
use_hyperparameter_search: false