# @package _global_

defaults:
  - model: whisper_tiny   
  - dataset: librispeech    
  - _self_

training:
  eval_strategy: epoch
  save_strategy: epoch
  num_train_epochs: 10
  max_steps: 1000

logging_path: logs