# @package _global_

logging_directory: "logs_inference"

asr_model_id: "openai/whisper-small
llm_base_model: "meta-llama/Llama-3-1b-Instruct"
llm_peft_path: "./model"

system_prompt: |
  You are an expert transcription editor converting messy ASR output into clean LaTeX. 
  Correct the user's spoken math into the exact LaTeX representation. 
  Output ONLY the LaTeX.

dataset_name: "marsianin500/Speech2Latex"
dataset_split: "sentences_test"
num_proc: 10

max_eval_samples: 500
batch_size: 8